on:
  push:
    branches:
      - develop
      - master

name: Test Coveralls

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: pnpm/action-setup@v6
        with:
          version: 10

      - uses: actions/checkout@v6

      - name: Use Node.js 24.x
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: pnpm

      - name: pnpm install
        run: pnpm install

      - name: pnpm test
        run: pnpm run test --config ./vitest.config.ts

      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
